In [3]:
import pandas as pd
import numpy as np 
import os
import seaborn as sns
from tqdm import tqdm
import time
import requests
import matplotlib.pyplot as plt

file_path_d = r"C:\Users\ADMIN\DME Dropbox\Park YR\project\Business Process Mining"

In [5]:
transaction = os.path.join(file_path_d, 'data', 'transactions.csv','transactions.csv')
transaction = pd.read_csv(transaction)
transaction

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_36084\3169763577.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  transaction = pd.read_csv(transaction)

          application_number event_code recorded_date
0                   02048602       SETS    2001-09-19
1                   03002534     LFLOST    2003-10-02
2                   03002534       SETS    2001-09-20
3                   03354872       SETS    2001-09-20
4                   03324609       SETS    2001-09-20
...                      ...        ...           ...
507392076           17089551       SMAL    2020-11-12
507392077           17089551       L194    2020-11-09
507392078           17089551       SCAN    2020-11-04
507392079           17089551       BIG.    2020-11-04
507392080           17089551       IEXX    2020-11-04

[507392081 rows x 3 columns]

In [6]:
eventcodes = os.path.join(file_path_d, 'data', 'event_codes.csv', 'event_codes.csv')
eventcodes = pd.read_csv(eventcodes)
eventcodes

      event_cd                                         event_desc
0         102P                                               102P
1         133P                                               133P
2         1744  Record that the application has been reactivated.
3         1750  Record withdrawal of an application by the app...
4         203I                                               203I
...        ...                                                ...
2189  XSREX141                                    Rescinded SB/69
2190      XT/D             Request for Extension of Time - Denied
2191      XT/G            Request for Extension of Time - Granted
2192      ZMAN               Petition for Writ of Mandamus (CAFC)
2193     ZMAND                                  Mandamus - Denied

[2194 rows x 2 columns]

In [7]:
application = os.path.join(file_path_d, 'data', 'application_data.csv', 'application_data.csv')
application = pd.read_csv(application)
application

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_36084\2590425114.py:2: DtypeWarning: Columns (0,3,4,6,12,13,14,16,17,18,21) have mixed types. Specify dtype option on import or set low_memory=False.
  application = pd.read_csv(application)

,application_number,filing_date,application_invention_type,examiner_full_name,examiner_art_unit,uspc_class,uspc_subclass,confirm_number,atty_docket_number,appl_status_desc,...,file_location_date,earliest_pgpub_number,earliest_pgpub_date,wipo_pub_number,wipo_pub_date,patent_number,patent_issue_date,invention_title,small_entity_indicator,aia_first_to_file
0,04453098,NaN,NaN,"LATEEF, MARVIN M",2106,338,254000,6933.0,NaN,Patented File - (Old Case Added for File Track...,...,1986-04-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNDISCOUNTED,NaN
1,04544040,NaN,NaN,"GLUCK, RICHARD E",3403,417,353000,9431.0,NaN,Patented File - (Old Case Added for File Track...,...,1999-06-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNDISCOUNTED,NaN
2,04577552,NaN,NaN,"LOOK, EDWARD K",3401,060,053000,1435.0,NaN,Patented File - (Old Case Added for File Track...,...,2008-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNDISCOUNTED,NaN
3,04589670,NaN,NaN,"NILSON, ROBERT G",3407,137,999999,1838.0,NaN,Patented File - (Old Case Added for File Track...,...,2008-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNDISCOUNTED,NaN
4,04578318,NaN,NaN,"HOWELL, DANIEL W",3722,409,163000,1455.0,NaN,ABANDONED - RESTORED,...,2016-11-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UNDISCOUNTED,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14100373,17913164,2023-05-31,Utility,NaN,NaN,NaN,NaN,4063.0,GUH-504US,Sent to Classification contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COMPOSITE CATALYST AND USE THEREOF IN PREPARIN...,SMALL,Other
14100374,17924829,2023-05-30,Utility,NaN,NaN,NaN,NaN,4148.0,50408-0067US1,Docketed New Case - Ready for Examination,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METHOD AND DEVICE FOR ENCODING/DECODING IMAGE ...,UNDISCOUNTED,Other
14100375,17998169,2023-05-26,Utility,NaN,NaN,NaN,NaN,3435.0,5576.403,Sent to Classification contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PIEZOELECTRIC COMPOSITE SUBSTRATE AND METHOD F...,UNDISCOUNTED,Other
14100376,18005586,2023-05-25,Utility,NaN,NaN,NaN,NaN,2934.0,KODKA27.043AP,Sent to Classification contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACTIVE ENERGY RAY-CURABLE INKJET PRINTING INK ...,UNDISCOUNTED,Other
14100377,17418722,2023-05-26,Utility,NaN,NaN,NaN,NaN,2603.0,1015.49PCT-US,Sent to Classification contractor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METHOD FOR PROVIDING FASHION ITEM RECOMMENDATI...,SMALL,Other

### merge dataset

In [8]:
event_log = transaction.merge(
    eventcodes,
    how='left',
    left_on='event_code',
    right_on='event_cd'
)

In [9]:
event_log

,application_number,event_code,recorded_date,event_cd,event_desc
0,02048602,SETS,2001-09-19,SETS,Set Application Status
1,03002534,LFLOST,2003-10-02,LFLOST,File Marked Lost
2,03002534,SETS,2001-09-20,SETS,Set Application Status
3,03354872,SETS,2001-09-20,SETS,Set Application Status
4,03324609,SETS,2001-09-20,SETS,Set Application Status
...,...,...,...,...,...
507392076,17089551,SMAL,2020-11-12,SMAL,Applicant Has Filed a Verified Statement of Sm...
507392077,17089551,L194,2020-11-09,L194,Cleared by OIPE CSR
507392078,17089551,SCAN,2020-11-04,SCAN,IFW Scan & PACR Auto Security Review
507392079,17089551,BIG.,2020-11-04,BIG.,ENTITY STATUS SET TO UNDISCOUNTED (INITIAL DEF...
507392080,17089551,IEXX,2020-11-04,IEXX,Initial Exam Team nn

In [11]:
event_log = event_log.drop(columns=['event_cd'])
event_log

,application_number,event_code,recorded_date,event_desc
0,02048602,SETS,2001-09-19,Set Application Status
1,03002534,LFLOST,2003-10-02,File Marked Lost
2,03002534,SETS,2001-09-20,Set Application Status
3,03354872,SETS,2001-09-20,Set Application Status
4,03324609,SETS,2001-09-20,Set Application Status
...,...,...,...,...
507392076,17089551,SMAL,2020-11-12,Applicant Has Filed a Verified Statement of Sm...
507392077,17089551,L194,2020-11-09,Cleared by OIPE CSR
507392078,17089551,SCAN,2020-11-04,IFW Scan & PACR Auto Security Review
507392079,17089551,BIG.,2020-11-04,ENTITY STATUS SET TO UNDISCOUNTED (INITIAL DEF...
507392080,17089551,IEXX,2020-11-04,Initial Exam Team nn

In [18]:
event_log_pm = event_log[
    ['application_number', 'event_code', 'recorded_date', 'event_desc']
].copy()

In [19]:
event_log_pm = event_log_pm.sort_values(
    ['application_number', 'recorded_date']
).reset_index(drop=True)
event_log_pm

,application_number,event_code,recorded_date,event_desc
0,3757645,FLRCPT.O,1981-12-18,Filing Receipt
1,3757645,L132,1981-12-18,Secrecy Order Imposed
2,3757645,L133,1982-07-22,Secrecy Order Renewed
3,3757645,L133,1983-07-19,Secrecy Order Renewed
4,3757645,L133,1984-07-19,Secrecy Order Renewed
...,...,...,...,...
507392076,PCT/ZA22/50013,MP210,2022-05-23,Mail International Search Report
507392077,PCT/ZA22/50013,MICR,2022-07-22,Applicant Has Filed a Verified Statement of Mi...
507392078,PCT/ZA22/50013,SMAL,2022-07-22,Applicant Has Filed a Verified Statement of Sm...
507392079,PCT/ZA22/50013,P224,2022-08-17,General Communication - No Other Forms Applicable
507392080,PCT/ZA22/50013,R5004,2023-06-08,Dispatch from PCT Operations - Chapter II

In [20]:
event_log_pm['event_order'] = (
    event_log_pm.groupby('application_number').cumcount() + 1
)
event_log_pm

,application_number,event_code,recorded_date,event_desc,event_order
0,3757645,FLRCPT.O,1981-12-18,Filing Receipt,1
1,3757645,L132,1981-12-18,Secrecy Order Imposed,2
2,3757645,L133,1982-07-22,Secrecy Order Renewed,3
3,3757645,L133,1983-07-19,Secrecy Order Renewed,4
4,3757645,L133,1984-07-19,Secrecy Order Renewed,5
...,...,...,...,...,...
507392076,PCT/ZA22/50013,MP210,2022-05-23,Mail International Search Report,15
507392077,PCT/ZA22/50013,MICR,2022-07-22,Applicant Has Filed a Verified Statement of Mi...,16
507392078,PCT/ZA22/50013,SMAL,2022-07-22,Applicant Has Filed a Verified Statement of Sm...,17
507392079,PCT/ZA22/50013,P224,2022-08-17,General Communication - No Other Forms Applicable,18
507392080,PCT/ZA22/50013,R5004,2023-06-08,Dispatch from PCT Operations - Chapter II,19

In [22]:
file_path_s = r"C:\Users\ADMIN\DME Dropbox\Park YR\project\Business Process Mining\data\G01_eventlog.tsv"
event_log_pm.to_csv(file_path_s, sep='\t')

In [24]:
test = os.path.join(file_path_d, 'data','G01_eventlog.tsv')
test = pd.read_csv(test, sep='\t', nrows=100)
test

,Unnamed: 0,application_number,event_code,recorded_date,event_desc,event_order
0,0,3757645,FLRCPT.O,1981-12-18,Filing Receipt,1
1,1,3757645,L132,1981-12-18,Secrecy Order Imposed,2
2,2,3757645,L133,1982-07-22,Secrecy Order Renewed,3
3,3,3757645,L133,1983-07-19,Secrecy Order Renewed,4
4,4,3757645,L133,1984-07-19,Secrecy Order Renewed,5
...,...,...,...,...,...,...
95,95,4217257,L135,1996-09-18,Security Classification Markings Removed,24
96,96,4217257,DOCK,1996-09-19,Case Docketed to Examiner in GAU,25
97,97,4217257,MN/=.,1996-09-26,Mail Notice of Allowance,26
98,98,4217257,N/=.,1996-09-26,Notice of Allowance Data Verification Completed,27
99,99,4217257,N084,1996-10-25,Issue Fee Payment Verified,28